experiment:
  name: "fcn_ecg_baseline"
  seed: 42
  device: "cuda"   # or "cpu"

# ========================
# DATA
# ========================
data:
  data_path: "data/"
  input_type: "ecg"   # ecg | multimodal
  use_data: "G" # G (all) | F(only female) | M(only male)
  use_tabular: false
  tabular_features: None # may be set to None

  # sampling_rate: 100
  num_leads: 12
  max_length: 1000

  batch_size: 64
  num_workers: 4

# ========================
# MODEL
# ========================
model:
  name: "fcn"   # fcn | resnet

# ========================
# TRAINING
# ========================
training:
  epochs: 20

  optimizer: "adam"
  lr: 0.001
  weight_decay: 1e-4

  scheduler: "step"   # none | step
  step_size: 10
  gamma: 0.5

  loss: "bce"
  pos_weight: 2.0 # can be set to 1

early_stopping:
    enabled: true
    monitor: "val_auc"   # val_auc | val_loss
    mode: "max"           # min (for loss), max (for auc)
    patience: 10

# ========================
# METRICS
# ========================
metrics:
  threshold: 0.5

# ========================
# LOGGING
# ========================
logging:
  log_dir: "logs/"
checkpoints:
  save_every: 1
  checkpoint_dir: "checkpoints/"
  checkpoint_path_for_load: "../checkpoints/fcn_ecg_baseline/model_epoch10.pt"
